language: node_js

node_js:
  - '10'

cache:
  yarn: true
  directories:
    - node_modules

install:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./codeclimate
  - chmod +x ./codeclimate
  - yarn install --silent

script:
  - ./codeclimate before-build

  - if [[ $TRAVIS_BRANCH == "master" ]]; then git checkout master && yarn release; fi

  - commitlint-travis
  - yarn lint
  - yarn test

  - NODE_ENV=production yarn build --bail

  - ./codeclimate format-coverage ./coverage/lcov.info --input-type lcov
  - ./codeclimate after-build --exit-code $TRAVIS_TEST_RESULT

after_deploy:
  - git remote rm origin
  - git remote add origin "https://hitmands:${GITHUB_ACCESS_TOKEN}@github.com/Code-Y/redux-fluent.git"
  - git push --follow-tags origin master

deploy:
  provider: npm
  skip_cleanup: true
  on:
    branch: master
  api_key: ${NPM_ACCESS_TOKEN}
  email: ${EMAIL}
